# Default values for influx-data-entry
# TODO: Phase 3 - Implement Helm values for configuration
# This will include:
# - Image repositories and tags
# - Resource limits and requests
# - Environment variables
# - Ingress configuration
# - Storage configuration

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Frontend configuration
frontend:
  image:
    repository: influx-data-entry-frontend
    tag: latest
    pullPolicy: IfNotPresent
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 5173
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: "http://api-service:8000"

# API configuration
api:
  image:
    repository: influx-data-entry-api
    tag: latest
    pullPolicy: IfNotPresent
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  env:
    INFLUXDB_URL: "http://influxdb-service:8086"

# InfluxDB configuration
influxdb:
  enabled: true
  
  image:
    repository: influxdb
    tag: "2.7"
    pullPolicy: IfNotPresent
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Grafana configuration
grafana:
  enabled: true
  
  image:
    repository: grafana/grafana
    tag: "10.4.2"
    pullPolicy: IfNotPresent
  
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: influx-data-entry.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend-service
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: api-service
            port: 8000
        - path: /grafana
          pathType: Prefix
          service:
            name: grafana-service
            port: 3000
  tls: []
